LANG.set({'ad_soyad' : 'Ad Soyad',
'alarm_aciklama1' : 'İncelemekte olduğunuz',
'alarm_aciklama2' : 'isimli ürünün fiyatı istediğiniz seviyeye düşünce size e-posta yoluyla haber verilecektir.',
'alarm_alarm_fiyat' : 'Alarm Fiyat',
'alarm_alarm_sure' : 'Alarm Süresi',
'alarm_guncel_fiyat' : 'Güncel Fiyat',
'alarm_uyari' : 'Lütfen Alt Ürün Seçiniz',
'alis_veris_listeme_ekle' : 'Alışveriş Listeme Ekle',
'alturun_stok_uyari' : 'Seçtiğiniz alt ürün stoklarımızda kalmamıştır!',
'aylik' : 'Aylık',
'baslik_yorum_ekle' : 'Yorum Ekle',
'beni_ara_alanlari_doldur' : 'Sizi aramamızı istiyorsanız lütfen alanları doldurunuz. ',
'coklu_urun_baslik' : 'Toptan alın indirim fırsatlarını yakalayın!',
'dahil' : 'Dahil',
'detay_agirlik' : 'Ağırlık(Kg)',
'detay_boyut' : 'Boyutlar(cm)',
'detay_garanti' : 'Garanti Bilgisi',
'detay_teslimat' : 'Teslimat Bilgisi',
'eposta' : 'E-Posta',
'fiyati' : 'Fiyatı',
'gonder' : 'Gönder',
'guvenlik_kodu' : 'Güvenlik Kodu',
'havale' : 'Havale',
'havale_ile' : 'Havale İle',
'hizli_mesaj_alanlari_doldur' : 'Hızlı mesaj göndermek istiyorsanız lütfen alanları doldurunuz.',
'indirim' : 'İndirim',
'indirimli' : 'İndirimli',
'indirimsiz_fiyat' : 'İndirimsiz Fiyatı',
'kazanacak_parapuan' : 'Kazanacağınız Parapuan',
'kazanciniz' : 'Kazancınız',
'kdv' : 'KDV',
'konu' : 'Konu',
'kredi_karti_tek_cekim' : 'Kredi Kartı Tek Ödeme',
'kredi_kartina' : 'Kredi Kartına',
'lutfen_alan_doldur' : 'Lütfen bu alanı doldurunuz',
'lutfen_giris_yap' : 'Lütfen giriş yapınız',
'mesaj' : 'Mesaj',
'miktar' : 'Miktar',
'oneri_aciklama_yetersiz' : 'Ürün açıklaması yetersiz / yanlış buluyorum',
'oneri_ayni_urun_var' : 'Bu ürüne / modele benzeyen ürün sitede var',
'oneri_box_aciklama' : 'Lütfen bu ürünün hakkında önerilerinizi, aşağıdaki ilgili alanları işaretleyerek ve eklemek istediğiniz açıklamanız eşliğinde bizlere ulaştırınız.Bu bölüme yazılan açıklamalar sitede yayınlanmaz.',
'oneri_box_tesekkur' : 'Ürün detay bilgilerinin iyileştirilmesi adına yardımlarınız için teşekkür ederiz.',
'oneri_diger' : 'Diğer',
'oneri_fiyat_pahali' : 'Bu ürünün fiyatı piyasaya göre daha pahalı',
'oneri_konu_seciniz' : 'Konu Seçiniz',
'oneri_resim_bulunamiyor' : 'Ürünün ayrıntılı resmini bulamıyorum',
'oneri_resim_yetersiz' : 'Ürünün resmi görüntülenemiyor veya çok yetersiz',
'oneri_urun_satilmamali' : 'Bu ürünün bu sitede satılmaması gerektiğini düşünüyorum',
'sepete_ekle' : 'Sepete Ekle',
'seviye_cokiyi' : 'Çok İyi',
'seviye_cokkotu' : 'Çok Kötü',
'seviye_fenadegil' : 'Fena Değil',
'seviye_iyi' : 'İyi',
'seviye_mukemmel' : 'Mükemmel',
'siparis_notu_ekle' : 'Not',
'stok_alturun_uyari' : 'Lütfen Bir Alt Ürün Seçiniz',
'stok_bildir' : 'Stoklara düşünce haber ver',
'stok_bildirim' : 'Ürün stoklarımıza düştüğünde kayıtlı e-postanıza bildirilecektir.',
'stokta_kalmadi' : 'Stokta Kalmadı',
'tab_alarm' : 'Fiyat Alarmı',
'tab_beni_ara' : 'Beni Ara',
'tab_dokuman' : 'Döküman',
'tab_dokunan' : 'Dökümanlar',
'tab_hizli_mesaj' : 'Hızlı Mesaj',
'tab_iliskili' : 'Kampanya',
'tab_odeme_secenekleri' : 'Ödeme Seçenekleri',
'tab_oneri_kutusu' : 'Öneri Kutusu',
'tab_resimler' : 'Resimler',
'tab_tavsiye_et' : 'Tavsiye Et',
'tab_urun_ozellikleri' : 'Ürün Özellikleri',
'tab_video' : 'Video',
'tab_yorumlar' : 'Yorumlar',
'taksit' : 'Taksit',
'taksit_tutar' : 'Taksit Tutar',
'tavsiye_ad' : 'Ad',
'tavsiye_alici_ad' : 'Alıcı Adı',
'tavsiye_alici_mail' : 'Alıcı E-Mail',
'tavsiye_et' : 'Tavsiye et',
'tavsiye_mail' : 'E-mail',
'tavsiye_mesaj' : 'Mesaj',
'tekcekim' : 'Tek Çekim',
'tel' : 'Telefon',
'toplam' : 'Toplam',
'toplam_tutar' : 'Toplam Tutar',
'urun_bulunamadi' : 'Aradığınız ürün bulunmamaktadır.',
'urun_bulunamadi_firsat' : 'Aradığınız fırsat ürününün süresi dolmuştur.',
'urun_etiketleri' : 'Ürün Etiketleri',
'urun_fiyat' : 'Ürün Fiyatı',
'urun_ozelligi_sec' : 'Ürünün Özelliğini Seçiniz',
'urun_resim' : 'Resim Yükleniyor.. Lütfen Bekleyin.',
'urun_resim_yuklendi' : 'Resim Başarıyla Yüklendi',
'uye_degil1' : 'Ürünlerle ilgili yorumlarınız  için lütfen sitemize ',
'uye_degil2' : ' yapınız.',
'yorum' : 'Yorum',
'yorum_basligi' : 'Yorum Başlığı',
'yorum_degerlendirme' : 'Değerlendirme',
'yorum_evethayir' : 'Yorumu onaylıyor musunuz?',
'yorum_isim' : 'Yorumda İsminiz Görünsün Mü?',
'yorum_oku_ust' : 'Yüzde oranları <b>Evet</b> yada <b>Hayır</b> seçen müşterilerimizin yüzde kaçının kayıtlı üyemiz olduğunu göstermektedir. Bu ürün için toplam',
'yorum_oku_ust2' : 'yorum yapılmıştır.',
'yorum_onay_mesaj' : 'Yorumunuz yönetici tarafından onaylandıktan sonra yayınlanacaktır. Teşekkür ederiz.',
'yorum_ortalama' : 'Ortalama',
'yorum_oylama1' : 'Teşekkürler yorum oylamanız kaydedilmiştir.',
'yorum_oylama2' : 'Diğer yorumlar için tıklayınız.',
'yorum_uye_giris' : 'Ürünlerle ilgili yorumlarınız  için lütfen sitemize',
'yorum_uye_giris2' : 'Giriş',
'yorum_uye_giris3' : 'yapınız',
'yorum_yaz1' : 'Teşekkürler Yorumunuz Kaydedilmiştir. Yorumunuz onaylandıktan sonra yayınlanacaktır.',
'yorum_yaz2' : 'Diğer yorumlar için tıklayınız.',
'yorum_yok1' : 'Ürün için henüz yorum eklenmemiştir. İlk yorumu eklemek için ',
'yorum_yok2' : 'lütfen buraya tıklayınız.',
'commercial_card' : 'Ticari Kart',
'select_image' : 'Resim Seç',
'not_selected_image' : 'Resim Seçilmedi !!!',
'upload' : 'Yükle',
 'x' : '' });